'use strict';

/**
 * BSEED TS0726-3-BS v5 canary overlay.
 *
 * Deployment:
 *   - keep the exact historical fleet converter (ef79...) unchanged;
 *   - load this file beside it;
 *   - this definition wins only for forward firmware 1.1.5-bseedv5.
 *
 * No configure callback below creates bindings or reporting.
 */

const {
    binary,
    deviceAddCustomCluster,
    deviceEndpoints,
    enumLookup,
    numeric,
    onOff,
    text,
} = require("zigbee-herdsman-converters/lib/modernExtend");
const e = require("zigbee-herdsman-converters/lib/exposes").presets;
const {Zcl} = require("zigbee-herdsman");

const withExposeLabel = (extend, label) => {
    for (const expose of extend.exposes || []) {
        if (typeof expose.withLabel === "function") expose.withLabel(label);
    }
    return extend;
};

const logicalOnOff = (endpointNames) => {
    const result = onOff({endpointNames, configureReporting: false});
    for (const expose of result.exposes || []) {
        if (expose.type === "switch") {
            for (const feature of expose.features || []) {
                if (feature.name === "state") {
                    feature.withLabel?.("Logical relay state");
                    feature.withDescription?.(
                        "Logical Zigbee On/Off state. This does not necessarily switch mains power: " +
                        "Physical relay behavior can force the electrical output Always on or Always off.",
                    );
                }
            }
        } else if (expose.name === "power_on_behavior") {
            expose.withLabel?.("Logical state after power-up");
            expose.withDescription?.(
                "Controls the logical Zigbee relay state after power-up. Physical relay behavior is " +
                "independent and can keep the electrical output Always on or Always off.",
            );
        }
    }
    return result;
};

const physicalRelayMode = (name, endpointName) => {
    const result = enumLookup({
        name,
        endpointName,
        lookup: {follow_state: 0, always_on: 1, always_off: 2},
        cluster: "genOnOff",
        attribute: {ID: 0xff03, type: 0x30},
        label: "Physical relay behavior",
        description:
            "Controls the electrical mains relay independently of the logical Zigbee On/Off state. " +
            "Follow state immediately synchronizes mains to the logical state. " +
            "Always on keeps the load energized and is recommended for smart bulbs/dimmers. " +
            "Always off keeps mains de-energized while logical state can still change. " +
            "Changing this setting can immediately switch mains power. The setting persists across restart.",
        entityCategory: "config",
    });
    for (const expose of result.exposes || []) expose.withProperty?.(name);
    return result;
};

const buttonType = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {toggle: 0, momentary: 1, momentary_nc: 2},
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff00, type: 0x30},
        label: "Button type",
        description:
            "Electrical type of the wall input: toggle/rocker, momentary push button, " +
            "or normally-closed momentary input.",
        entityCategory: "config",
    });

const buttonCommandBehavior = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {
            on_off: 0,
            off_on: 1,
            toggle_simple: 2,
            toggle_smart_sync: 3,
            toggle_smart_opposite: 4,
        },
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0x0010, type: 0x30, required: true, write: true, min: 0, max: 4},
        label: "Button command behavior",
        description:
            "Defines the On/Off command generated by this wall input. toggle_simple sends Toggle; " +
            "smart modes send explicit On/Off based on the local logical relay state.",
        entityCategory: "config",
    });

const localRelayTrigger = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {detached: 0, press_start: 1, short_press: 3, long_press: 2},
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff01, type: 0x30},
        label: "Local relay trigger",
        description:
            "Controls when this button changes its assigned local LOGICAL relay state. " +
            "This is independent of Physical relay behavior; mains can remain Always on.",
        entityCategory: "config",
    });

const localRelayIndex = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {relay_1: 1, relay_2: 2, relay_3: 3},
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff02, type: 0x20},
        label: "Assigned local relay",
        description:
            "Selects the logical local relay state changed by this button: " +
            "relay_1 = Left, relay_2 = Middle, relay_3 = Right.",
        entityCategory: "config",
    });

const boundDeviceTrigger = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {press_start: 1, short_press: 3, long_press: 2},
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff05, type: 0x30},
        label: "Bound-device trigger",
        description:
            "Controls when this button sends direct Zigbee commands to existing bindings/groups.",
        entityCategory: "config",
    });

const longPressThreshold = (name, endpointName) =>
    numeric({
        name,
        endpointNames: [endpointName],
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff03, type: 0x21},
        label: "Long-press threshold",
        description: "How long the button must be held before it is treated as a long press.",
        unit: "ms",
        valueMin: 0,
        valueMax: 5000,
        entityCategory: "config",
    });

const holdDimmingSpeed = (name, endpointName) =>
    numeric({
        name,
        endpointNames: [endpointName],
        cluster: "genOnOffSwitchCfg",
        attribute: {ID: 0xff04, type: 0x20},
        label: "Hold dimming speed",
        description: "Brightness-change rate sent in Zigbee Level Control Move commands while held.",
        unit: "level/s",
        valueMin: 1,
        valueMax: 255,
        entityCategory: "config",
    });

const indicatorBehavior = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        lookup: {
            logical_state: 0,
            inverse_logical_state: 1,
            manual: 2,
            physical_output: 3,
            binding_status: 4,
        },
        cluster: "genOnOff",
        attribute: {ID: 0xff01, type: 0x30},
        label: "Indicator LED source",
        description:
            "Selects what the panel LED represents. Logical state follows the local Zigbee relay state " +
            "(legacy value 0); Inverse logical state preserves legacy inverse behavior (value 1). " +
            "Manual uses Indicator LED state. Physical output follows the effective mains command: " +
            "Always on = LED on, Always off = LED off, Follow state = logical state. Binding status " +
            "follows the locally tracked intended On/Off state of direct-binding commands. " +
            "Binding status is local intent, not confirmation that a remote lamp actually changed. " +
            "On canonical v5 firmware these choices control only the panel LED, never the mains relay.",
        entityCategory: "config",
    });

const bindingIntentState = (name, endpointName) =>
    binary({
        name,
        endpointName,
        valueOn: ["ON", 1],
        valueOff: ["OFF", 0],
        cluster: "genOnOff",
        attribute: {ID: 0xff04, type: 0x10},
        label: "Bound-light intent state",
        description:
            "Locally tracked intended On/Off state of commands sent through this button's direct binding. " +
            "Firmware updates it only after an accepted command with a matching binding. It is not proof " +
            "of the remote light's actual state. Home Assistant or another controller may write the actual " +
            "target state here to reconcile the indicator; writing this value does not send a bound-device " +
            "command and does not change logical relay state or mains power.",
        access: "ALL",
        entityCategory: "config",
    });

const indicatorState = (name, endpointName) =>
    binary({
        name,
        endpointName,
        valueOn: ["ON", 1],
        valueOff: ["OFF", 0],
        cluster: "genOnOff",
        attribute: {ID: 0xff02, type: 0x10},
        label: "Indicator LED state",
        description: "Manual panel-LED state; used only when Indicator LED source is Manual.",
        access: "ALL",
        entityCategory: "config",
    });

const lastButtonAction = (name, endpointName) =>
    enumLookup({
        name,
        endpointName,
        access: "STATE_GET",
        lookup: {released: 0, press: 1, long_press: 2, position_on: 3, position_off: 4},
        cluster: "genMultistateInput",
        attribute: "presentValue",
        label: "Last button action",
        description: "Most recently reported physical button input state.",
        entityCategory: "diagnostic",
    });

const networkIndicator = (name, endpointName) =>
    binary({
        name,
        endpointName,
        valueOn: ["ON", 1],
        valueOff: ["OFF", 0],
        cluster: "genBasic",
        attribute: {ID: 0xff01, type: 0x10},
        label: "Network indicator",
        description: "Controls the dedicated network-status indicator LED.",
        access: "ALL",
        entityCategory: "config",
    });

const multiPressResetCount = (name, endpointName) =>
    numeric({
        name,
        endpointNames: [endpointName],
        cluster: "genBasic",
        attribute: {ID: 0xff02, type: 0x20},
        label: "Factory-reset press count",
        description: "Consecutive presses required for factory reset. Set to 0 to disable.",
        valueMin: 0,
        valueMax: 255,
        entityCategory: "config",
    });

const DEVICE_CONFIG_CHUNK_MAX = 24;
let deviceConfigTransaction = 0;

const configTransportCluster = () =>
    deviceAddCustomCluster("bseedBasicTransport", {
        name: "bseedBasicTransport",
        ID: 0x0000,
        attributes: {},
        commands: {
            deviceConfigStage: {
                name: "deviceConfigStage",
                ID: 0xf0,
                parameters: [{name: "data", type: Zcl.BuffaloZclDataType.LIST_UINT8}],
            },
            deviceConfigCommit: {
                name: "deviceConfigCommit",
                ID: 0xf1,
                parameters: [{name: "data", type: Zcl.BuffaloZclDataType.LIST_UINT8}],
            },
        },
        commandsResponse: {},
    });

const validateDeviceConfig = (value) => {
    if (typeof value !== "string") throw new Error("device_config must be a string");
    if (value.length < 4 || value.length >= 128) {
        throw new Error("device_config must contain 4..127 printable ASCII characters");
    }
    for (const ch of value) {
        const code = ch.charCodeAt(0);
        if (code < 0x20 || code > 0x7e) {
            throw new Error("device_config accepts printable ASCII only");
        }
    }
    if (!value.endsWith(";")) {
        throw new Error("device_config must end with ';'");
    }
    const tokens = value.slice(0, -1).split(";");
    if (tokens.length < 2 || tokens.some((token) => token.length === 0)) {
        throw new Error("device_config contains an empty/invalid token");
    }
    return Buffer.from(value, "ascii");
};

const crc16CcittFalse = (bytes) => {
    let crc = 0xffff;
    for (const byte of bytes) {
        crc ^= byte << 8;
        for (let bit = 0; bit < 8; bit++) {
            crc = crc & 0x8000 ? ((crc << 1) ^ 0x1021) & 0xffff : (crc << 1) & 0xffff;
        }
    }
    return crc;
};

const deviceConfigEditable = (name, endpointName) => {
    const result = withExposeLabel(
        text({
            name,
            endpointName,
            access: "ALL",
            cluster: "genBasic",
            attribute: {ID: 0xff00, type: 0x44},
            description:
                "Advanced Romasku hardware pin map. Editing this can disconnect buttons/indicators, " +
                "switch mains unexpectedly, or require recovery firmware. v5 sends edits through a " +
                "validated transactional chunk protocol because the full configuration is too large for " +
                "a reliable single Zigbee write. The device validates length, syntax, complete coverage " +
                "and CRC before replacing NVM, then reboots. Change only with a known recovery path.",
            zigbeeCommandOptions: {timeout: 30_000},
            entityCategory: "diagnostic",
        }),
        "Advanced hardware configuration",
    );

    result.toZigbee = [
        {
            key: [name],
            convertGet: async (entity, key, meta) => {
                await meta.device.getEndpoint(1).read("genBasic", [0xff00], {timeout: 30_000});
            },
            convertSet: async (entity, key, value, meta) => {
                const bytes = validateDeviceConfig(value);
                const endpoint = meta.device.getEndpoint(1);
                const tx = (deviceConfigTransaction % 255) + 1;
                deviceConfigTransaction = tx;
                const options = {disableDefaultResponse: false, timeout: 30_000};

                for (let offset = 0; offset < bytes.length; offset += DEVICE_CONFIG_CHUNK_MAX) {
                    const chunk = [...bytes.subarray(offset, offset + DEVICE_CONFIG_CHUNK_MAX)];
                    await endpoint.command(
                        "bseedBasicTransport",
                        "deviceConfigStage",
                        {data: [tx, offset, chunk.length, ...chunk]},
                        options,
                    );
                }

                const crc = crc16CcittFalse(bytes);
                await endpoint.command(
                    "bseedBasicTransport",
                    "deviceConfigCommit",
                    {data: [tx, bytes.length, crc & 0xff, crc >> 8]},
                    options,
                );
                return {state: {[key]: value}};
            },
        },
    ];
    result.configure = [];
    return result;
};

const legacyActionEvent = () => {
    const switches = [
        {endpoint: 1, prefix: "switch_0", name: "switch_left"},
        {endpoint: 2, prefix: "switch_1", name: "switch_middle"},
        {endpoint: 3, prefix: "switch_2", name: "switch_right"},
    ];
    const states = {
        0: "release",
        1: "press",
        2: "long_press",
        3: "position_on",
        4: "position_off",
    };
    const onOffCommands = {commandOn: "on", commandOff: "off", commandToggle: "toggle"};
    const levelSuffixes = ["brightness_move_up", "brightness_move_down", "brightness_stop"];
    const prefixes = Object.fromEntries(switches.map((item) => [item.endpoint, item.prefix]));
    const names = Object.fromEntries(switches.map((item) => [item.endpoint, item.name]));

    const perButtonValues = [
        ...Object.values(states),
        ...Object.values(onOffCommands),
        ...levelSuffixes,
    ];
    const aggregateValues = [];
    for (const item of switches) {
        for (const suffix of perButtonValues) {
            aggregateValues.push(item.prefix + "_" + suffix);
        }
    }

    const result = (msg, suffix) => {
        const prefix = prefixes[msg.endpoint.ID];
        const name = names[msg.endpoint.ID];
        if (prefix === undefined || name === undefined || suffix === undefined) return;
        return {
            action: prefix + "_" + suffix,
            ["action_" + name]: suffix,
        };
    };

    return {
        isModernExtend: true,
        exposes: [
            e.action(aggregateValues),
            ...switches.map((item) => e.action(perButtonValues).withEndpoint(item.name)),
        ],
        fromZigbee: [
            {
                cluster: "genMultistateInput",
                type: ["attributeReport", "readResponse"],
                convert: (model, msg) => result(msg, states[msg.data.presentValue]),
            },
            {
                cluster: "genOnOff",
                type: Object.keys(onOffCommands),
                convert: (model, msg) => result(msg, onOffCommands[msg.type]),
            },
            {
                cluster: "genLevelCtrl",
                type: ["commandMove", "commandMoveWithOnOff", "commandStop", "commandStopWithOnOff"],
                convert: (model, msg) => {
                    const stop = msg.type === "commandStop" || msg.type === "commandStopWithOnOff";
                    const suffix = stop
                        ? "brightness_stop"
                        : "brightness_move_" + (msg.data.movemode === 0 ? "up" : "down");
                    return result(msg, suffix);
                },
            },
        ],
    };
};

module.exports = [
    {
        fingerprint: [
            {
                manufacturerName: "iedhxgyi",
                modelID: "TS0726-3-BS",
                softwareBuildID: "1.1.5-bseedv5",
                priority: 100,
            },
        ],
        model: "EC-GL86ZPCS31",
        vendor: "Tuya-custom",
        description: "BSEED Echo Click / Scale 3-gang — Romasku v5 canary",
        extend: [
            configTransportCluster(),
            deviceEndpoints({
                endpoints: {
                    switch_left: 1,
                    switch_middle: 2,
                    switch_right: 3,
                    relay_left: 4,
                    relay_middle: 5,
                    relay_right: 6,
                },
            }),

            logicalOnOff(["relay_left", "relay_middle", "relay_right"]),

            physicalRelayMode("relay_left_physical_mode", "relay_left"),
            physicalRelayMode("relay_middle_physical_mode", "relay_middle"),
            physicalRelayMode("relay_right_physical_mode", "relay_right"),

            buttonType("switch_left_mode", "switch_left"),
            buttonCommandBehavior("switch_left_action_mode", "switch_left"),
            localRelayTrigger("switch_left_relay_mode", "switch_left"),
            localRelayIndex("switch_left_relay_index", "switch_left"),
            boundDeviceTrigger("switch_left_binded_mode", "switch_left"),
            longPressThreshold("switch_left_long_press_duration", "switch_left"),
            holdDimmingSpeed("switch_left_level_move_rate", "switch_left"),

            buttonType("switch_middle_mode", "switch_middle"),
            buttonCommandBehavior("switch_middle_action_mode", "switch_middle"),
            localRelayTrigger("switch_middle_relay_mode", "switch_middle"),
            localRelayIndex("switch_middle_relay_index", "switch_middle"),
            boundDeviceTrigger("switch_middle_binded_mode", "switch_middle"),
            longPressThreshold("switch_middle_long_press_duration", "switch_middle"),
            holdDimmingSpeed("switch_middle_level_move_rate", "switch_middle"),

            buttonType("switch_right_mode", "switch_right"),
            buttonCommandBehavior("switch_right_action_mode", "switch_right"),
            localRelayTrigger("switch_right_relay_mode", "switch_right"),
            localRelayIndex("switch_right_relay_index", "switch_right"),
            boundDeviceTrigger("switch_right_binded_mode", "switch_right"),
            longPressThreshold("switch_right_long_press_duration", "switch_right"),
            holdDimmingSpeed("switch_right_level_move_rate", "switch_right"),

            indicatorBehavior("relay_left_indicator_mode", "relay_left"),
            bindingIntentState("relay_left_binding_intent", "relay_left"),
            indicatorState("relay_left_indicator", "relay_left"),
            indicatorBehavior("relay_middle_indicator_mode", "relay_middle"),
            bindingIntentState("relay_middle_binding_intent", "relay_middle"),
            indicatorState("relay_middle_indicator", "relay_middle"),
            indicatorBehavior("relay_right_indicator_mode", "relay_right"),
            bindingIntentState("relay_right_binding_intent", "relay_right"),
            indicatorState("relay_right_indicator", "relay_right"),

            lastButtonAction("switch_left_press_action", "switch_left"),
            lastButtonAction("switch_middle_press_action", "switch_middle"),
            lastButtonAction("switch_right_press_action", "switch_right"),
            legacyActionEvent(),

            networkIndicator("network_led", "switch_left"),
            multiPressResetCount("multi_press_reset_count", "switch_left"),
            deviceConfigEditable("device_config", "switch_left"),
        ],
        meta: {multiEndpoint: true},
        configure: async () => {},
        ota: true,
    },
];
