#!/usr/bin/env python3
from pathlib import Path

p = Path("zigbee2mqtt/converters/bseed_ts0726_v5.js")
s = p.read_text(encoding="utf-8")

def replace(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f"missing marker: {label}")
    s = s.replace(old, new, 1)

replace(
    'const e = require("zigbee-herdsman-converters/lib/exposes").presets;\n',
    'const exposes = require("zigbee-herdsman-converters/lib/exposes");\n'
    'const e = exposes.presets;\n'
    'const ea = exposes.access;\n',
    "exposes import",
)

replace(
    '"Logical Zigbee On/Off state. This does not necessarily switch mains power: " +\n'
    '                        "Physical relay behavior can force the electrical output Always on or Always off.",',
    '"The Zigbee state for this channel. Use it for automations and state tracking. " +\n'
    '                        "It is not the same as mains power: with Mains power behavior set to Always on, " +\n'
    '                        "this may be OFF while the smart load remains continuously powered.",',
    "logical state help",
)

replace(
    '"Controls the logical Zigbee relay state after power-up. Physical relay behavior is " +\n'
    '                "independent and can keep the electrical output Always on or Always off.",',
    '"Chooses the Zigbee state restored after restart. This affects the logical channel only. " +\n'
    '                "It never overrides Mains power behavior, so Always on remains electrically powered.",',
    "startup help",
)

s = s.replace('label: "Physical relay behavior",', 'label: "Mains power behavior",')
replace(
    '"Controls the electrical mains relay independently of the logical Zigbee On/Off state. " +\n'
    '            "Follow state immediately synchronizes mains to the logical state. " +\n'
    '            "Always on keeps the load energized and is recommended for smart bulbs/dimmers. " +\n'
    '            "Always off keeps mains de-energized while logical state can still change. " +\n'
    '            "Changing this setting can immediately switch mains power. The setting persists across restart.",',
    '"Controls the actual electrical output for this channel. For smart bulbs and smart dimmers choose Always on " +\n'
    '            "so they stay powered while logical state changes. Follow state is for a load this device should physically switch. " +\n'
    '            "Always off keeps the output de-energized. Changing this can affect power immediately, so verify the connected load first. " +\n'
    '            "The choice survives restart.",',
    "mains help",
)

replace(
    '"Electrical type of the wall input: toggle/rocker, momentary push button, " +\n'
    '            "or normally-closed momentary input.",',
    '"Match this to the wall mechanism. Toggle is a maintained rocker; Momentary is a normal push button; " +\n'
    '            "Momentary NC is normally closed. A wrong choice makes presses appear inverted or unreliable.",',
    "button type help",
)

replace('label: "Button command behavior",', 'label: "Direct-binding command",', "binding label")
replace(
    '"Defines the On/Off command generated by this wall input. toggle_simple sends Toggle; " +\n'
    '            "smart modes send explicit On/Off based on the local logical relay state.",',
    '"Chooses the command sent directly to bound lights. Toggle simple sends Zigbee Toggle and depends least on local state. " +\n'
    '            "Smart sync sends explicit On/Off to match the local logical state; Smart opposite sends the inverse. " +\n'
    '            "On/off and Off/on are mainly useful with maintained rocker inputs.",',
    "binding help",
)

replace('label: "Local relay trigger",', 'label: "Update local state",', "local trigger label")
replace(
    '"Controls when this button changes its assigned local LOGICAL relay state. " +\n'
    '            "This is independent of Physical relay behavior; mains can remain Always on.",',
    '"Chooses when this physical button updates the assigned Zigbee state. Detached never changes local state. " +\n'
    '            "Press start updates immediately; Short press after a completed click; Long press only after the hold threshold. " +\n'
    '            "This does not override Mains power behavior.",',
    "local trigger help",
)

replace('label: "Assigned local relay",', 'label: "Local state channel",', "relay label")
replace(
    '"Selects the logical local relay state changed by this button: " +\n'
    '            "relay_1 = Left, relay_2 = Middle, relay_3 = Right.",',
    '"Chooses which local Zigbee channel this button updates: Relay 1 = Left, Relay 2 = Middle, Relay 3 = Right. " +\n'
    '            "This affects logical state only and does not remap physical GPIO pins.",',
    "relay help",
)

replace('label: "Bound-device trigger",', 'label: "Control bound light",', "bound trigger label")
replace(
    '"Controls when this button sends direct Zigbee commands to existing bindings/groups.",',
    '"Chooses when the button sends a direct command to existing bindings or groups. Press start is fastest; " +\n'
    '            "Short press waits for a completed click; Long press sends only after a hold. This does not create or remove bindings.",',
    "bound trigger help",
)

replace('label: "Long-press threshold",', 'label: "Hold threshold",', "hold label")
replace(
    'description: "How long the button must be held before it is treated as a long press.",',
    'description: "How long the button must stay pressed before it becomes a long press. Increase it to reduce accidental holds; decrease it for faster hold actions.",',
    "hold help",
)

replace('label: "Hold dimming speed",', 'label: "Dimming speed",', "dimming label")
replace(
    'description: "Brightness-change rate sent in Zigbee Level Control Move commands while held.",',
    'description: "Speed of direct-binding brightness changes while held. Higher values dim faster; lower values give finer control.",',
    "dimming help",
)

replace('label: "Indicator LED source",', 'label: "LED shows",', "led label")
old_led = '''            "Selects what the panel LED represents. Logical state follows the local Zigbee relay state " +
            "(legacy value 0); Inverse logical state preserves legacy inverse behavior (value 1). " +
            "Manual uses Indicator LED state. Physical output follows the effective mains command: " +
            "Always on = LED on, Always off = LED off, Follow state = logical state. Binding status " +
            "follows the locally tracked intended On/Off state of direct-binding commands. " +
            "Binding status is local intent, not confirmation that a remote lamp actually changed. " +
            "On canonical v5 firmware these choices control only the panel LED, never the mains relay.",'''
new_led = '''            "Chooses what the small panel LED represents. Logical state follows this channel's Zigbee state. " +
            "Inverse logical state shows the opposite. Manual lets you control the LED separately. Physical output shows " +
            "the electrical-output command. Binding status is recommended when this button directly controls a smart light: " +
            "it follows locally tracked On/Off intent sent through the binding. It is intent, not confirmation of remote state. " +
            "These options control only the panel LED and never change the electrical output.",'''
replace(old_led, new_led, "led help")

replace('label: "Bound-light intent state",', 'label: "Bound light state (tracked)",', "intent label")
old_intent = '''            "Locally tracked intended On/Off state of commands sent through this button's direct binding. " +
            "Firmware updates it only after an accepted command with a matching binding. It is not proof " +
            "of the remote light's actual state. Home Assistant or another controller may write the actual " +
            "target state here to reconcile the indicator; writing this value does not send a bound-device " +
            "command and does not change logical relay state or mains power.",'''
new_intent = '''            "The On/Off state this device currently believes the bound light should be in. Direct-binding commands update it locally, " +
            "and Home Assistant can correct it from the real light state. Use it with LED shows = Binding status. " +
            "It is not remote-state confirmation by itself. Changing this only corrects the local tracker: it sends no command, " +
            "changes no binding and never changes electrical power.",'''
replace(old_intent, new_intent, "intent help")

replace('label: "Indicator LED state",', 'label: "Manual LED state",', "manual led label")
replace(
    'description: "Manual panel-LED state; used only when Indicator LED source is Manual.",',
    'description: "Turns the panel LED on or off when LED shows is Manual. It has no effect in other LED modes and never controls power.",',
    "manual led help",
)
replace('label: "Last button action",', 'label: "Last button input",', "last action label")
replace(
    'description: "Most recently reported physical button input state.",',
    'description: "Diagnostic view of the most recent physical input event seen by firmware. Useful for checking wiring and input mode.",',
    "last action help",
)
replace('label: "Network indicator",', 'label: "Network LED",', "network label")
replace(
    'description: "Controls the dedicated network-status indicator LED.",',
    'description: "Controls the separate network-status LED. This is independent of the three channel LEDs.",',
    "network help",
)
replace(
    'description: "Consecutive presses required for factory reset. Set to 0 to disable.",',
    'description: "Consecutive presses required for factory reset. Set to 0 to disable press-based reset. Change only if you have another recovery method.",',
    "reset help",
)

replace(
    'const DEVICE_CONFIG_CHUNK_MAX = 24;\nlet deviceConfigTransaction = 0;',
    '''const DEVICE_CONFIG_CHUNK_MAX = 24;
const DEVICE_CONFIG_UNLOCK_MS = 60_000;
let deviceConfigTransaction = 0;
const deviceConfigUnlocks = new Map();

const deviceConfigDeviceKey = (meta) => {
    const ieee = meta?.device?.ieeeAddr;
    if (!ieee) throw new Error("Cannot identify device for advanced configuration lock");
    return ieee;
};

const deviceConfigUnlock = () => ({
    isModernExtend: true,
    exposes: [
        exposes
            .enum("device_config_unlock", ea.SET, ["enable_editing"])
            .withLabel("Enable advanced editing")
            .withDescription(
                "Unlocks Hardware configuration for this device for 60 seconds. The button itself changes nothing. " +
                "A valid save consumes the unlock immediately. If transfer fails, unlock again before retrying. " +
                "Restarting Zigbee2MQTT also returns the editor to locked.",
            )
            .withCategory("config"),
    ],
    fromZigbee: [],
    toZigbee: [
        {
            key: ["device_config_unlock"],
            convertSet: async (entity, key, value, meta) => {
                if (value !== "enable_editing") throw new Error("Unsupported advanced-editing action");
                deviceConfigUnlocks.set(deviceConfigDeviceKey(meta), Date.now() + DEVICE_CONFIG_UNLOCK_MS);
                return {};
            },
        },
    ],
    configure: [],
});

const requireDeviceConfigUnlock = (meta) => {
    const key = deviceConfigDeviceKey(meta);
    const expiresAt = deviceConfigUnlocks.get(key) || 0;
    if (Date.now() >= expiresAt) {
        deviceConfigUnlocks.delete(key);
        throw new Error(
            "Hardware configuration is locked. Click 'Enable advanced editing' and save again within 60 seconds.",
        );
    }
    return key;
};''',
    "unlock implementation",
)

start = s.index("const validateDeviceConfig = (value) => {")
end = s.index("\n\nconst crc16CcittFalse", start)
s = s[:start] + '''const validateDeviceConfig = (value) => {
    if (typeof value !== "string") throw new Error("Hardware configuration must be text");
    if (value.length < 4 || value.length >= 128) {
        throw new Error("Hardware configuration must contain 4..127 printable ASCII characters");
    }
    for (const ch of value) {
        const code = ch.charCodeAt(0);
        if (code < 0x20 || code > 0x7e) {
            throw new Error("Hardware configuration accepts printable ASCII only");
        }
    }
    if (!value.endsWith(";")) throw new Error("Hardware configuration must end with ';'");

    const tokens = value.slice(0, -1).split(";");
    if (tokens.some((token) => token.length === 0)) {
        throw new Error("Hardware configuration contains an empty token");
    }
    if (tokens[0] !== "iedhxgyi" || tokens[1] !== "TS0726-3-BS") {
        throw new Error("Manufacturer and model must remain iedhxgyi / TS0726-3-BS");
    }

    const entries = tokens.slice(2);
    const network = entries.filter((token) => /^L[A-E][0-7]i?$/.test(token));
    const switches = entries.filter((token) => /^S[A-E][0-7][uUdDfFnN]$/.test(token));
    const relays = entries.filter((token) => /^R[A-E][0-7]([A-E][0-7])?$/.test(token));
    const indicators = entries.filter((token) => /^I[A-E][0-7]i?$/.test(token));
    const momentary = entries.filter((token) => token === "M");
    const recognized = new Set([...network, ...switches, ...relays, ...indicators, ...momentary]);
    const unknown = entries.filter((token) => !recognized.has(token));
    if (unknown.length) {
        throw new Error("Unsupported token(s) for this BSEED 3-gang board: " + unknown.join(", "));
    }
    if (network.length !== 1 || switches.length !== 3 || relays.length !== 3 || indicators.length !== 3 || momentary.length !== 1) {
        throw new Error("This board must keep exactly 1 network LED, 3 switch inputs, 3 relay outputs, 3 channel LEDs and the M marker");
    }

    const pins = [];
    for (const token of network) pins.push(token.slice(1, 3));
    for (const token of switches) pins.push(token.slice(1, 3));
    for (const token of indicators) pins.push(token.slice(1, 3));
    for (const token of relays) {
        pins.push(token.slice(1, 3));
        if (token.length === 5) pins.push(token.slice(3, 5));
    }
    const duplicates = pins.filter((pin, index) => pins.indexOf(pin) !== index);
    if (duplicates.length) {
        throw new Error("GPIO pin(s) assigned more than once: " + [...new Set(duplicates)].join(", "));
    }

    return Buffer.from(value, "ascii");
};''' + s[end:]

replace(
    '''            description:
                "Advanced Romasku hardware pin map. Editing this can disconnect buttons/indicators, " +
                "switch mains unexpectedly, or require recovery firmware. v5 sends edits through a " +
                "validated transactional chunk protocol because the full configuration is too large for " +
                "a reliable single Zigbee write. The device validates length, syntax, complete coverage " +
                "and CRC before replacing NVM, then reboots. Change only with a known recovery path.",''',
    '''            description:
                "Current low-level hardware map for this exact BSEED 3-gang device. Editing is locked by default: first click " +
                "Enable advanced editing, then save within 60 seconds. Before Zigbee traffic is sent, the converter checks identity, " +
                "required 3-gang structure, token syntax and duplicate GPIO assignments. Firmware then checks all chunks and CRC before " +
                "replacing NVM and rebooting. A valid save consumes the unlock. Wrong pin assignments can still require recovery firmware.",''',
    "advanced description",
)

replace(
    '''            convertSet: async (entity, key, value, meta) => {
                const bytes = validateDeviceConfig(value);
                const endpoint = meta.device.getEndpoint(1);''',
    '''            convertSet: async (entity, key, value, meta) => {
                const bytes = validateDeviceConfig(value);
                const unlockKey = requireDeviceConfigUnlock(meta);
                deviceConfigUnlocks.delete(unlockKey);
                const endpoint = meta.device.getEndpoint(1);''',
    "unlock enforcement",
)

replace(
    '''            networkIndicator("network_led", "switch_left"),
            multiPressResetCount("multi_press_reset_count", "switch_left"),
            deviceConfigEditable("device_config", "switch_left"),''',
    '''            networkIndicator("network_led", "switch_left"),
            multiPressResetCount("multi_press_reset_count", "switch_left"),

            // Advanced section: deliberately last and locked by default.
            deviceConfigUnlock(),
            deviceConfigEditable("device_config", "switch_left"),''',
    "advanced order",
)

replace(
    'description: "BSEED Echo Click / Scale 3-gang — Romasku v5 canary",',
    'description: "BSEED 3-gang smart-light controller — protected mains control, direct binding and advanced configuration",',
    "device description",
)

p.write_text(s, encoding="utf-8")
